### ISSUE TITLE
Make `branch_name` with remote configuration parameterized by `required_remote` name

### ISSUE THREAD

**Issue by uvsmtid** [uvsmtid/git-group#12]
At the moment the branch name is specified statically in `conf.yaml`:

```
required_remote: some_remote                  # <-- current remote
...
remote_config:                                                                  
    repository_id: .                                                            
    branch_name: git-group-config-some_remote # <-- branch with remote configuration
```

However, branch with remote configuration is not mergeable (its content is unique to specific remote).
Therefore, normally every change in `required_remote` parameter needs corresponding changes to `branch_name` under `remote_config`.

It is more convenient to parameterize:

```
required_remote: some_remote
...
remote_config:                                                                  
    repository_id: .                                                            
    branch_name: 'git-group-config-%(required_remote)s'
```
